### PR TITLE
Fixing Padding

### PR DESCRIPTION
**Pull request by Nexushunter**
### Changes
Changed the padding within the shades widget.

### Reason
Noticed that the colours were pushed together on a smaller display

### Usage 
[My File Manager Project](https://github.com/NexisHunter/filer_flutter/blob/master/lib/widgets/settings_drawer.dart)

### CODE REVIEW

**Comment by Pyozer** [comment]
Hi !
Thank you for your pull request, I will check this soon and merge it ;)

**Comment by Nexushunter** [comment]
No problem and keep up the good work. Love the package!

**Comment by Pyozer** [comment]
After recheck this package, it seem that adding padding on shades is not good, because it's already manage by Grid and the main and shade colors have not same size anymore 😢

I add possibility to provide the space between colors, and fixed missing space value in number of colors per line calculation.
You can update to `1.0.2` 😉

**Comment by Nexushunter** [comment]
Sounds good.

**Pull request merged**
